server:
  port: 8761
spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://config-server:8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    org.springframework: DEBUG